version: '2.4'

services:
  supervisor:
    build: 
      context: .
      dockerfile: Dockerfile-arm64
  backend_1:
    build: 
      context: .
      dockerfile: Dockerfile-arm64
  frontend_1:
    build:
      context: ./rcongui
      dockerfile: Dockerfile-arm64
  redis:
    image: arm64v8/redis:5
  postgres:
    image: arm64v8/postgres:12
